name: Generate and deploy content to pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Generate site
        run: |
          pip install -r requirements.txt
          python ./generate.py
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './out/'
      - name: Deploy to github pages
        id: deploy
        uses: actions/deploy-pages@v4
